Add context for APN if not present

diff --git a/cards/generic-qmi-device b/cards/generic-qmi-device
--- a/cards/generic-qmi-device
+++ b/cards/generic-qmi-device
@@ -34,6 +34,7 @@ setup() {
   SERIAL_DEV=/dev/ttyUSB2
   # cdc device used by qmicli/libqmi
   CDC_DEV=/dev/cdc-wdm0
+  CHAT_TIMEOUT=5
   RUNDIR="/run/$(basename "$0")"
   FIELDS="handle CID"
   return $?
@@ -63,17 +64,21 @@ init() {
     return 1
   fi
 
-  echo "checking power state"
+  verbose "checking power state"
   # not sure what to do with this, can't find qmi_dms_power_state_build_string_from_mask def
   # for now just dump it to the console
-  qmicli -p --device="${CDC_DEV}" --dms-get-power-state
+  msg=$(qmicli -p --device="${CDC_DEV}" --dms-get-power-state)
+  # can't find definition of this enum
+  # Power state: 'external-source'
+	# Battery level: '0 %'
+  verbose "$msg"
 
 
-  echo "get operating mode"
+  verbose "get operating mode"
   RETVAL=1
   for i in $(seq 1 6); do
     if qmicli -p --device="${CDC_DEV}" --dms-get-operating-mode | grep -q 'online' ; then
-      echo "modem is online"
+      verbose "modem is online"
       RETVAL=0
       break
      else
@@ -106,6 +111,7 @@ unlock() {
   #
   # Failure is fatal and will cause wwan-helper to exit with an error.
 
+  verbose "unlock sim"
   if [ "$PIN" ] ; then
     qmicli -p --device="${CDC_DEV}" --dms-uim-verify-pin="PIN,${PIN}"
   fi
@@ -117,26 +123,74 @@ register() {
   #
   # The function must block until the SIM is registered.
 
-  # not doing anything yet
-  echo "register step"
-  qmicli -p --device="${CDC_DEV}" --uim-get-card-status | grep 'Application state'
+  # With the Telit LE910C4, SIM registration is done with the "default" PDP context,
+  # and whatever APN it defines, rather than the APN defined with the "connect" command.
+  # If the default APN cannot be reached (because for example the SIM is bound to a private
+  # APN) the connect call will fail. See
+  # https://lists.freedesktop.org/archives/libqmi-devel/2020-November/003480.html
 
-  echo "operator name"
-  qmicli -p --device="${CDC_DEV}" --nas-get-operator-name
+  # To fix:
+  # 1) ensure a PDP context for the user APN exists
+  # 2) make it the default if so configured
+
+  #TODO: support 3gpp2
+  profile=-1
+  for i in $(seq 0 1) ; do
+    apns=$(qmicli -p --device="${CDC_DEV}" --wds-get-profile-list=3gpp | grep 'APN:' | grep -Eo "'.*'" | tr -d "'")
+    # apns="m2m.com.attz ims sos attm2mglobal"
+    j=1
+    for apn in $apns; do
+      if (echo "$apn" | grep -i "${APN}" ) ; then
+        verbose "${apn} matches ${APN}, profile=${j}"
+        profile="$j"
+        break 2
+      fi
+      j=$((j+1))
+    done
+    # didn't break, so no profile for this apn
+    verbose "No profile found for APN ${APN}; creating new profile..."
+    # create a profile then loop again to find the profile index
+    if [ "$IF_WWAN_ALLOW_ROAMING" = "false" ] ; then
+      qmicli -p --device="${CDC_DEV}" --wds-create-profile=3gpp,apn="${APN}",pdp-type=IPV4V6,auth=NONE,no-roaming=yes,disabled=no || return $?
+    else
+      qmicli -p --device="${CDC_DEV}" --wds-create-profile=3gpp,apn="${APN}",pdp-type=IPV4V6,auth=NONE,no-roaming=no,disabled=no || return $?
+    fi
+    verbose "done, retval $?"
+  done
+
+  default_profile=$(qmicli -p --device="${CDC_DEV}" --wds-get-default-profile-number=3gpp | grep 'Default profile number:' | grep -Eo "'.*'" | tr -d "'")
+  if [ "$profile" -ne "$default_profile" ] ; then
+    verbose "Setting $profile as the default profile"
+    qmicli -p --device="${CDC_DEV}" --wds-set-default-profile-number="3gpp,${profile}" || return $?
+  fi
+
+
+  # not doing anything yet
+  verbose "register step"
+  # TODO: there can be multiple SIMs slots, should support selection
+  msg=$(qmicli -p --device="${CDC_DEV}" --uim-get-card-status)
+  if (echo "$msg" | grep 'Application state' | grep 'ready') ; then
+    verbose "$msg"
+    verbose "SIM is ready"
+  else
+    echo "SIM not ready."
+  fi
+
+  msg=$(qmicli -p --device="${CDC_DEV}" --nas-get-operator-name)
+  verbose "$msg"
+
 
   RETVAL=1
-  echo "RSSI"
+  verbose "RSSI"
   for i in $(seq 1 12) ; do
-    NETWORK=$(qmicli -p --device="${CDC_DEV}" --nas-get-signal-strength)
-    #FIXME: cannot attach to network on LTE even though it is better. Only
-    # test for 'umts' for now. When fixed, add -e lte
-    if echo "$NETWORK" | grep -e 'umts' -e 'lte' ; then
-      echo "network up"
+    network=$(qmicli -p --device="${CDC_DEV}" --nas-get-signal-strength)
+    if echo "$network" | grep -e 'umts' -e 'lte' ; then
+      verbose "network up"
       RETVAL=0
       break
     else
-      echo "$NETWORK"
-      echo "waiting to acquire network..."
+      verbose "$network"
+      verbose "waiting to acquire network..."
       sleep 5
     fi
   done
@@ -154,7 +208,7 @@ connect() {
   # with an error.
 
   mkdir -p "${RUNDIR}"
-  if [ -d "${RUNDIR}" ] ; then echo "storing state in ${RUNDIR}" ; else echo "rundir missing" ; fi
+  if [ -d "${RUNDIR}" ] ; then verbose "storing state in ${RUNDIR}" ; else verbose "rundir missing" ; fi
 
   RESULT=$(qmicli -p --device="${CDC_DEV}" --wds-start-network="ip-type=4,apn=${APN}" --client-no-release-cid)
   ERR=$?
@@ -162,9 +216,9 @@ connect() {
     for FIELD in $FIELDS ; do 
      VALUE=$(echo "${RESULT}" | grep -E -o "${FIELD}: ?'[0-9]+'" | grep -E -o "[0-9]+") && echo "${VALUE}" > "${RUNDIR}/${FIELD}" || return $?
     done
-    echo "modem attached to network"
+    verbose "modem attached to network"
   else
-    echo "modem failed to attach to network"
+    verbose "modem failed to attach to network"
     return "$ERR"
   fi
 
@@ -175,8 +229,31 @@ connect() {
   # but techship says its ok
   # https://techship.com/faq/how-to-step-by-step-set-up-a-data-connection-over-qmi-interface-using-qmicli-and-in-kernel-driver-qmi-wwan-in-linux/
 
+  # alternative:
+  # qmicli -p --device="${CDC_DEV}" --wds-get-current-settings
+  # IP Family: IPv4
+  # IPv4 address: 10.65.8.3
+  # IPv4 subnet mask: 255.255.255.248
+  # IPv4 gateway address: 10.65.8.4
+  # MTU: 1430
+  # Domains: none
+
+  ipdata_path="${RUNDIR}/ipdata"
+  qmicli -p --device="${CDC_DEV}" --wds-get-current-settings > "${ipdata_path}" || (echo "no current settings" ; return $? )
+  ip_addr=$(grep 'IPv4 address:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
+  ip_mask=$(grep 'IPv4 subnet mask:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
+  ip_gateway=$(grep 'IPv4 gateway address:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
+  ip_mtu=$(grep 'MTU:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
+
+  # complicated and broken
+  #ip address add "${ip_addr}/${ip_mask}" dev wwan0
+  #ip link set dev wwan0 mtu "${ip_mtu}"
+  #ip route add default via "${ip_gateway}"
+
+  # wrong but easy and works
   udhcpc -q -f -n -i wwan0 || return $?
   
+
   # Insert user-defined dns servers if appropriate
   if [ "$IF_DNS_NAMESERVERS" ] ; then
     # often /etc/resolv.conf -> /tmp/resolv.conf on embedded
@@ -230,7 +307,7 @@ disconnect() {
   # shut down modem
   # FIELDS="handle CID"
   readvars || return $?
-  echo "shutting down connection with handle=${HANDLE}, CID=${CID}"
+  verbose "shutting down connection with handle=${HANDLE}, CID=${CID}"
   qmicli -p --device="${CDC_DEV}" --wds-stop-network="${HANDLE}" --client-cid="${CID}"
   rm "${RUNDIR}/handle"
   rm "${RUNDIR}/CID"
@@ -245,7 +322,7 @@ shutdown() {
   #
   # Failure is *not* fatal and in case of an error, wwan-helper will just
   # finish and pretend the world is all in order.
-  echo "shutdown"
+  verbose "shutdown"
   rmdir "${RUNDIR}"
   :
 }
@@ -257,6 +334,6 @@ teardown() {
   # Note that this step is called after both connect() and disconnect().
   #
   # Failure is fatal and will cause wwan-helper to exit with an error.
-  echo "teardown"
+  verbose "teardown"
   :
 }
