Support user-defined dns servers

diff --git a/cards/generic-qmi-device b/cards/generic-qmi-device
--- a/cards/generic-qmi-device
+++ b/cards/generic-qmi-device
@@ -33,8 +33,6 @@ setup() {
   SERIAL_DEV=/dev/cdc-wdm0
   RUNDIR="/run/$(basename "$0")"
   FIELDS="handle CID"
-
-  mkdir -p "${RUNDIR}"
   return $?
 }
 
@@ -100,7 +98,10 @@ connect() {
   # Failure is fatal and will cause wwan-helper to retry, unless the user
   # didn't configure retires, in which case it will cause wwan-helper to exit
   # with an error.
-  
+
+  mkdir -p "${RUNDIR}"
+  if [ -d "${RUNDIR}" ] ; then echo "storing state in ${RUNDIR}" ; else echo "rundir missing" ; fi
+
   RESULT=$(qmicli -p --device="${SERIAL_DEV}" --wds-start-network="ip-type=4,apn=${APN}" --client-no-release-cid)
   ERR=$?
   if [ "$ERR" -eq 0 ] ; then 
@@ -109,19 +110,32 @@ connect() {
     done
     echo "modem attached to network"
   else
-    echo "failed to attach to network"
-    return $?
+    echo "modem failed to attach to network"
+    return "$ERR"
   fi
 
-  ip link set "${IFACE}" up
-  
+  ip link set "${IFACE}" up || return $?
+
   # some people think you shouldn't use dhcp
   # https://lists.freedesktop.org/archives/libqmi-devel/2020-April/003263.html
   # but techship says its ok
   # https://techship.com/faq/how-to-step-by-step-set-up-a-data-connection-over-qmi-interface-using-qmicli-and-in-kernel-driver-qmi-wwan-in-linux/
-  udhcpc -q -f -n -i wwan0
+
+  udhcpc -q -f -n -i wwan0 || return $?
   
-  # ip addr
+  # Insert user-defined dns servers if appropriate
+  if [ "$IF_DNS_NAMESERVERS" ] ; then
+    # often /etc/resolv.conf -> /tmp/resolv.conf on embedded
+    RESOLV_PATH=$(realpath /etc/resolv.conf)
+    TMP_PATH=$(mktemp)
+    echo "# created by $0" > "$TMP_PATH"
+    for NAMESERVER in $IF_DNS_NAMESERVERS; do
+      echo "nameserver ${NAMESERVER}" >> "$TMP_PATH"
+    done
+    cp "$RESOLV_PATH" "$RUNDIR"
+    mv "$TMP_PATH" "$RESOLV_PATH"
+  fi
+  return $?
 }
 
 reset() {
@@ -148,11 +162,22 @@ disconnect() {
   # Failure is *not* fatal and in case of an error, wwan-helper will just
   # proceed to shut down the card.
  
-  # FIELDS="handle CID"
+  # restore DNS
+  TMP_PATH="${RUNDIR}/resolv.conf"
+  if [ -e "${TMP_PATH}" ] ; then
+    RESOLV_PATH=$(realpath /etc/resolv.conf)
+    mv "$TMP_PATH" "$RESOLV_PATH"
+  fi
 
+  # bring down interface
+  ip link set "${IFACE}" down || return $?
+
+  # shut down modem
+  # FIELDS="handle CID"
   readvars || return $?
-  ip link set "${IFACE}" down || (echo "ip link down failed" ; return $?)
+  echo "shutting down connection with handle=${HANDLE}, CID=${CID}"
   qmicli -p --device="${SERIAL_DEV}" --wds-stop-network="${HANDLE}" --client-cid="${CID}"
+  rm -rf "${RUNDIR}/*"
   return $?
 }
 
@@ -164,6 +189,8 @@ shutdown() {
   #
   # Failure is *not* fatal and in case of an error, wwan-helper will just
   # finish and pretend the world is all in order.
+  echo "shutdown"
+  rm -rf "${RUNDIR}"
   :
 }
 
@@ -171,6 +198,9 @@ teardown() {
   # Optional steps to tear-down the handler script, e.g. removing temporary
   # files, etc.
   #
+  # Note that this step is called after both connect() and disconnect().
+  #
   # Failure is fatal and will cause wwan-helper to exit with an error.
-  rm -rf "${RUNDIR}"
+  echo "teardown"
+  :
 }
