Replace logging uses of echo with verbose()

diff --git a/cards/generic-modemmanager-device b/cards/generic-modemmanager-device
--- a/cards/generic-modemmanager-device
+++ b/cards/generic-modemmanager-device
@@ -31,8 +31,8 @@ setup() {
 }
 
 readvars() {
-  MODEM=$(cat "${RUNDIR}/Modem") || (ERR="$?"; echo "could not read cached Modem"; return "$ERR")
-  SIM=$(cat "${RUNDIR}/SIM") || (ERR="$?"; echo "could not read cached SIM" ; return "$ERR")
+  MODEM=$(cat "${RUNDIR}/Modem") || (ERR="$?"; verbose "could not read cached Modem"; return "$ERR")
+  SIM=$(cat "${RUNDIR}/SIM") || (ERR="$?"; verbose "could not read cached SIM" ; return "$ERR")
   return 0
 }
 
@@ -44,27 +44,27 @@ init() {
   #
   # Failure is fatal and will cause wwan-helper to exit with an error.
 
-  echo "RUNDIR is ${RUNDIR}"
+  verbose "RUNDIR is ${RUNDIR}"
   mkdir -p "${RUNDIR}"
 
   mmcli --scan-modems || return $?
   # what if more than one modem? For now, take the first
-  RESULT=$(mmcli --list-modems | grep -E -o '/org/freedesktop/ModemManager1/Modem/[0-9]+') || (ERR="$?"; echo "no modem"; return "$ERR")
+  RESULT=$(mmcli --list-modems | grep -E -o '/org/freedesktop/ModemManager1/Modem/[0-9]+') || (ERR="$?"; verbose "no modem"; return "$ERR")
   MODEM=$(basename "$(echo "${RESULT}" | head -n1)")
   echo "${MODEM}" > "${RUNDIR}/Modem"
   # what if more than one modem? For now, take the first
-  RESULT=$(mmcli --modem "${MODEM}" | grep -E -o '/org/freedesktop/ModemManager1/SIM/[0-9]+') || (ERR="$?"; echo "no sim"; return "$ERR")
+  RESULT=$(mmcli --modem "${MODEM}" | grep -E -o '/org/freedesktop/ModemManager1/SIM/[0-9]+') || (ERR="$?"; verbose "no sim"; return "$ERR")
   SIM=$(basename "$(echo "${RESULT}" | head -n1)")
   echo "${SIM}" > "${RUNDIR}/SIM"
   
   if (mmcli -m "${MODEM}" | grep -q 'power state: on') ; then
-    echo "modem is on"
+    verbose "modem is on"
   else
-    echo "powering on modem"
-    mmcli -m "${MODEM}" --set-power-state-on || (ERR="$?"; echo "could not set modem power state on"; return "$ERR")
+    verbose "powering on modem"
+    mmcli -m "${MODEM}" --set-power-state-on || (ERR="$?"; verbose "could not set modem power state on"; return "$ERR")
   fi
 
-  mmcli -m "${MODEM}" --enable || (ERR="$?"; echo "could not enable modem"; return "$ERR")
+  mmcli -m "${MODEM}" --enable || (ERR="$?"; verbose "could not enable modem"; return "$ERR")
 }
 
 unlock() {
@@ -79,11 +79,11 @@ unlock() {
   # Failure is fatal and will cause wwan-helper to exit with an error.
   
   if [ "${PIN}" ] ; then
-    echo "unlocking sim"
+    verbose "unlocking sim"
     readvars || return $?
     mmcli --modem="${MODEM}" --sim="${SIM}" --pin="${PIN}" || return $?
   else
-    echo "no pin defined, assuming sim is unlocked"
+    verbose "no pin defined, assuming sim is unlocked"
   fi
   return 0
   
@@ -96,7 +96,7 @@ register() {
   # The function must block until the SIM is registered.
 
 
-  echo FIXME: will need to active sim on some carriers
+  verbose FIXME: will need to active sim on some carriers
   :
 }
 
@@ -112,19 +112,19 @@ connect() {
 
   if [ "${APN}" ] ; then
     readvars || return $?
-    mmcli -m "${MODEM}" --simple-connect="apn=${APN},ip-type=ipv4" || (ERR="$?"; echo "simple-connect failed" ; return "$ERR")
+    mmcli -m "${MODEM}" --simple-connect="apn=${APN},ip-type=ipv4" || (ERR="$?"; verbose "simple-connect failed" ; return "$ERR")
   else
-    echo "Expected wwan-apn in /etc/network/interfaces"
+    verbose "Expected wwan-apn in /etc/network/interfaces"
     return 1
   fi
-  echo "activing iface ${IFACE}"
-  ip link set "${IFACE}" up || (ERR="$?"; echo "ip link up failed"; return "$ERR")
+  verbose "activing iface ${IFACE}"
+  ip link set "${IFACE}" up || (ERR="$?"; verbose "ip link up failed"; return "$ERR")
   
   # some people think you shouldn't use dhcp
   # https://lists.freedesktop.org/archives/libqmi-devel/2020-April/003263.html
   # but techship says its ok
   # https://techship.com/faq/how-to-step-by-step-set-up-a-data-connection-over-qmi-interface-using-qmicli-and-in-kernel-driver-qmi-wwan-in-linux/
-  udhcpc -q -f -n -i wwan0  || (ERR="$?"; echo "udhcpc failed"; return "$ERR")
+  udhcpc -q -f -n -i wwan0  || (ERR="$?"; verbose "udhcpc failed"; return "$ERR")
   return 0
 }
 
@@ -154,7 +154,7 @@ disconnect() {
   #
   # Failure is *not* fatal and in case of an error, wwan-helper will just
   # proceed to shut down the card.
-  ip link set "${IFACE}" down || (ERR="$?"; echo "ip link down failed"; return "$ERR")
+  ip link set "${IFACE}" down || (ERR="$?"; verbose "ip link down failed"; return "$ERR")
   readvars || return $?
   mmcli -m "${MODEM}" --simple-disconnect || return $?
   rm -rf "${RUNDIR}"
diff --git a/cards/generic-qmi-device b/cards/generic-qmi-device
--- a/cards/generic-qmi-device
+++ b/cards/generic-qmi-device
@@ -41,8 +41,8 @@ setup() {
 }
 
 readvars() {
-  HANDLE=$(cat "${RUNDIR}/handle") || (ERR="$?"; echo "could not read cached handle"; return "$ERR")
-  CID=$(cat "${RUNDIR}/CID") || (ERR="$?"; echo "could not read cached CID" ; return "$ERR")
+  HANDLE=$(cat "${RUNDIR}/handle") || (ERR="$?"; verbose "could not read cached handle"; return "$ERR")
+  CID=$(cat "${RUNDIR}/CID") || (ERR="$?"; verbose "could not read cached CID" ; return "$ERR")
   return 0
 }
 
@@ -60,7 +60,7 @@ init() {
   ip link set "$IFACE" down
 
   if ! (lsusb -t | grep -q qmi_wwan) ; then
-    echo "qmi driver is not loaded"
+    verbose "qmi driver is not loaded"
     return 1
   fi
 
@@ -82,7 +82,7 @@ init() {
       RETVAL=0
       break
      else
-      echo "${i}: setting operation mode online"
+      verbose "${i}: setting operation mode online"
       sleep 5
       qmicli -p --device="${CDC_DEV}" --dms-set-operating-mode='online'
     fi
@@ -180,7 +180,7 @@ register() {
     verbose "$msg"
     verbose "SIM is ready"
   else
-    echo "SIM not ready."
+    verbose "SIM not ready."
   fi
 
   msg=$(qmicli -p --device="${CDC_DEV}" --nas-get-operator-name)
@@ -246,7 +246,7 @@ connect() {
   # Domains: none
 
   ipdata_path="${RUNDIR}/ipdata"
-  qmicli -p --device="${CDC_DEV}" --wds-get-current-settings > "${ipdata_path}" || (echo "no current settings" ; return $? )
+  qmicli -p --device="${CDC_DEV}" --wds-get-current-settings > "${ipdata_path}" || (verbose "no current settings" ; return $? )
   ip_addr=$(grep 'IPv4 address:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
   ip_mask=$(grep 'IPv4 subnet mask:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
   ip_gateway=$(grep 'IPv4 gateway address:' "${ipdata_path}" | cut -d: -f2 | tr -d ' ' )
